location                 = "westeurope"
location_short           = "weu"
env                      = "preprod"
dbsku                    = "B_Standard_B1ms"
dbsize                   = "20"
dbversion                = "8.0.21"
storage_account_tier     = "Standard"
storage_replication_type = "LRS"
